on:
  push:
    branches:
      main

jobs:
  pycharm_c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jetbrains Projector Docker
        uses: actions/checkout@v2
        with: 
          repository: JetBrains/projector-docker
          path: projector
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone Projector Core
        run: projector/clone-projector-core.sh

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tonypepe/pycharm:latest
          build-args: |
              buildGradle=true
              "downloadUrl=https://download.jetbrains.com/python/pycharm-community-2021.2.1.tar.gz"
          context: 'projector'
      




