on:
  push:
    branches:
      main

jobs:
  pycharm_c:
    runs-on: ubuntu-latest
    env:
      VERSION: "2021.2.1"
    steps:
      - name: Checkout Jetbrains Projector Docker
        uses: actions/checkout@v2
        with: 
          repository: JetBrains/projector-docker
          path: projector-docker
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone Projector Core
        working-directory: ./projector-docker
        run: ./clone-projector-core.sh

      - name: Build Conatainer
        working-directory: ./projector-docker
        run: |
          ./build-container.sh "${{ secrets.DOCKERHUB_USERNAME }}/pycharmc:latest" "https://download.jetbrains.com/python/pycharm-community-${{ env.VERSION }}.tar.gz"
      
      - name: Tag Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pycharm:latest ${{ secrets.DOCKERHUB_USERNAME }}/pycharmc${{ env.VERSION }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pycharmc:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pychermc:${{ env.VERSION }}

