on:
  push:
    branches:
      main

jobs:
  pycharm_c:
    runs-on: ubuntu-latest
    env: 
      VERSION: "2021.2.1"
      IMAGE_NAME: "pycharmc"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Checkout Jetbrains Projector Docker
        uses: actions/checkout@v2
        with: 
          repository: JetBrains/projector-docker
          path: projector-docker
      
      - name: Replace Dockerfile
        run: |
          copy repo/Dockerfile projector-docker/Dockerfile
          cat projector-docker/Dockerfile
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone Projector Core
        working-directory: ./projector-docker
        run: ./clone-projector-core.sh

      - name: Build Conatainer
        working-directory: ./projector-docker
        run: |
          ./build-container.sh "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest" "https://download.jetbrains.com/python/pycharm-community-${{ env.VERSION }}.tar.gz"
      
      - name: Tag Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

