on:
  push:
    branches:
      main

jobs:
  pycharm_c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jetbrains Projector Docker
        uses: actions/checkout@v2
        with: 
          repository: JetBrains/projector-docker
          path: projector-docker
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone Projector Core
        working-directory: ./projector-docker
        run: ./clone-projector-core.sh

      - name: Build Conatainer
        working-directory: ./projector-docker
        run: |
          ./build-container.sh "tonypepe/pycharmc:latest" "https://download.jetbrains.com/python/pycharm-community-2021.2.1.tar.gz"
      
      - name: Push Image
        run: |
          docker push tonypepe/pycharmc:latest
      # - name: Build and Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: tonypepe/pycharm:latest
      #     build-args: |
      #         buildGradle=true
      #         "downloadUrl=https://download.jetbrains.com/python/pycharm-community-2021.2.1.tar.gz"
      #     file: ./projector/Dockerfile
      #     context: .
      




